server:
  port: 8080
  servlet:
    context-path: /api
## http://localhost:8080/api/swagger-ui/index.html#/
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cvanalyzer
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: 123

    data:
      elasticsearch:
        repositories:
          enabled:  false  # ← Désactive /active  Elasticsearch

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  jwtSecret: "y9w!2Kf8Xn$1vR@pCz7^Gh#0Lk@8wMq%RandomExtraCharactersToMakeItLongEnough1234567890"
  jwtExpirationMs: 86400000
  jwtIssuer: cv-analyzer-api
  storage:
    location: ./uploads
  nlp:
    models-dir: classpath:/nlp-models
    annotators: tokenize, ssplit, pos, lemma, ner, regexner

